{ self }:
{ config, lib, pkgs, ... }:

# NixOS module: NPU-backed embedding service for graphrag-rs.
#
# Stands up:
#   - An OpenVINO Model Server container serving a static-shape embedding
#     model on /v3/embeddings (OpenAI-compatible).
#   - A oneshot that builds the static-shape model + tokenizer + Mediapipe
#     graph the first time it runs (and again whenever model/seq_len/pooling
#     /device options change).
#
# Distilled from the in-house `mneme` flake's openvino.nix. Generalized
# (drops mneme's vault-mcp/qdrant integration and excludePatterns/etc. that
# were specific to mneme's home-walking indexer) so this flake stands alone.
#
# Pair with the home-manager module's `services.graphrag-rs.embedding.backend
# = "ollama"` once the Ollama→OVMS shim is also deployed (TODO). Until then,
# the OVMS endpoint at http://127.0.0.1:<ports.openvino>/v3/embeddings is
# OpenAI-compatible and can be hit directly by anything that supports the
# OpenAI embeddings API.

let
  cfg = config.services.graphrag-rs-npu;

  # NPU support requires the -gpu image variant; the plain image is CPU-only.
  ovmsImage = "openvino/model_server:2026.0-gpu";
  pythonImage = "python:3.12-slim";

  # In-container Python that builds the static-shape OVMS model:
  #   1. optimum-cli export <MODEL> → staging (FP/INT8 IR, dynamic shapes)
  #   2. core.read_model + reshape to [1, SEQ_LEN] → static IR
  #   3. Convert HF tokenizer → OV tokenizer + detokenizer (with padding
  #      forced to SEQ_LEN — required for static shapes on NPU 3)
  #   4. Hand-write Mediapipe graph.pbtxt (EmbeddingsCalculatorOV)
  #   5. Hand-write models/config.json referencing the graph
  pullPyScript = pkgs.writeText "graphrag-ovms-pull.py" ''
    """Build a static-shape OVMS embeddings model. See nixos.nix header for context."""
    import json
    import os
    import shutil
    import subprocess
    from pathlib import Path

    MODEL = os.environ["GRS_MODEL"]
    SEQ_LEN = int(os.environ["GRS_SEQ_LEN"])
    POOLING = os.environ["GRS_POOLING"]
    DEVICE = os.environ["GRS_DEVICE"]

    MODELS = Path("/models")
    STAGING = MODELS / ".staging"
    EMB = MODELS / "embeddings"

    if STAGING.exists():
        shutil.rmtree(STAGING)
    if EMB.exists():
        shutil.rmtree(EMB)
    EMB.mkdir(parents=True)

    print(f"[1/6] Exporting {MODEL} via optimum-cli (INT8) → {STAGING}")
    subprocess.check_call([
        "optimum-cli", "export", "openvino",
        "--model", MODEL,
        "--task", "feature-extraction",
        "--weight-format", "int8",
        "--library", "transformers",
        "--trust-remote-code",
        str(STAGING),
    ])

    import openvino as ov
    core = ov.Core()
    print(f"[2/6] Reading IR + reshaping inputs to [1, {SEQ_LEN}]")
    model = core.read_model(str(STAGING / "openvino_model.xml"))
    model.reshape({p.get_any_name(): [1, SEQ_LEN] for p in model.inputs})

    print(f"[3/6] Saving static IR → {EMB}/openvino_model.xml")
    ov.save_model(model, str(EMB / "openvino_model.xml"), compress_to_fp16=False)

    print("[4/6] Converting HF tokenizer → OpenVINO tokenizer + detokenizer")
    from openvino_tokenizers import convert_tokenizer
    from transformers import AutoTokenizer
    hf_tok = AutoTokenizer.from_pretrained(MODEL, trust_remote_code=True)
    # Force max_length so the converted OV tokenizer pads to that shape. NPU 3
    # needs every input tensor at compile-time-known shapes; without this,
    # short inputs become e.g. [1, 7] and the EmbeddingsCalculatorOV's
    # RET_CHECK fails when feeding the static [1, SEQ_LEN] model.
    hf_tok.model_max_length = SEQ_LEN
    for kwargs in [
        dict(with_detokenizer=True, use_max_padding=True),
        dict(with_detokenizer=True, max_length=SEQ_LEN, use_max_padding=True),
        dict(with_detokenizer=True, max_length=SEQ_LEN, pad_to_max_length=True, truncation=True),
        dict(with_detokenizer=True),
    ]:
        try:
            ov_tok, ov_detok = convert_tokenizer(hf_tok, **kwargs)
            print(f"  convert_tokenizer kwargs that worked: {sorted(kwargs)}")
            break
        except TypeError as e:
            print(f"  convert_tokenizer rejected {sorted(kwargs)}: {e}")
            continue
    else:
        raise RuntimeError("no convert_tokenizer parameter set succeeded")
    ov.save_model(ov_tok,   str(EMB / "openvino_tokenizer.xml"))
    ov.save_model(ov_detok, str(EMB / "openvino_detokenizer.xml"))

    print(f"[5/6] Writing graph.pbtxt (EmbeddingsCalculatorOV, target_device={DEVICE}, pooling={POOLING})")
    graph_pbtxt = (
        "# Generated by graphrag-rs-npu (nixos module)\n"
        f"# model={MODEL} seq_len={SEQ_LEN} pooling={POOLING} device={DEVICE}\n"
        "input_stream: \"REQUEST_PAYLOAD:input\"\n"
        "output_stream: \"RESPONSE_PAYLOAD:output\"\n"
        "node {\n"
        f"    name: \"{MODEL}\",\n"
        "    calculator: \"EmbeddingsCalculatorOV\"\n"
        "    input_side_packet: \"EMBEDDINGS_NODE_RESOURCES:embeddings_servable\"\n"
        "    input_stream: \"REQUEST_PAYLOAD:input\"\n"
        "    output_stream: \"RESPONSE_PAYLOAD:output\"\n"
        "    node_options: {\n"
        "        [type.googleapis.com / mediapipe.EmbeddingsCalculatorOVOptions]: {\n"
        "            models_path: \"./\",\n"
        "            normalize_embeddings: true,\n"
        # truncate=true clips/pads inputs to the model's static seq_len.
        # Required for NPU 3 (baked-static shapes); harmless on dynamic IRs.
        "            truncate: true,\n"
        f"            pooling: {POOLING},\n"
        f"            target_device: \"{DEVICE}\",\n"
        "            plugin_config: '{\"NUM_STREAMS\":\"1\"}',\n"
        "        }\n"
        "    }\n"
        "}\n"
    )
    (EMB / "graph.pbtxt").write_text(graph_pbtxt)

    print("[6/6] Writing /models/config.json")
    config = {
        "model_config_list": [],
        "mediapipe_config_list": [
            {"name": "embeddings", "graph_path": "/models/embeddings/graph.pbtxt"}
        ],
    }
    (MODELS / "config.json").write_text(json.dumps(config, indent=2))

    shutil.rmtree(STAGING, ignore_errors=True)
    print("Done.")
  '';

  # Idempotent wrapper around the export container. The stamp file encodes
  # (model, seq_len, pooling, device); rebuild kicks in only when one changes.
  pullScript = pkgs.writeShellApplication {
    name = "graphrag-ovms-pull";
    runtimeInputs = [ pkgs.podman pkgs.coreutils ];
    text = ''
      set -euo pipefail
      MODELS_DIR="${cfg.stateDir}/ovms-models"
      STAMP_FILE="$MODELS_DIR/.graphrag-stamp"
      STAMP="model=${cfg.embeddingModel} seq=${toString cfg.embeddingMaxSeqLen} pool=${cfg.embeddingPooling} dev=${cfg.embeddingDevice}"

      mkdir -p "$MODELS_DIR"

      if [ -f "$MODELS_DIR/config.json" ] \
         && [ -f "$MODELS_DIR/embeddings/openvino_model.xml" ] \
         && [ -f "$STAMP_FILE" ] \
         && [ "$(cat "$STAMP_FILE")" = "$STAMP" ]; then
        echo "[graphrag-ovms-pull] config matches stamp, skipping rebuild."
        echo "  $STAMP"
        exit 0
      fi

      echo "[graphrag-ovms-pull] Building embedding model:"
      echo "  $STAMP"

      ${pkgs.podman}/bin/podman run --rm \
        --user=0:0 \
        --workdir /tmp \
        -v "$MODELS_DIR":/models:rw \
        -v ${pullPyScript}:/pull.py:ro \
        -e GRS_MODEL="${cfg.embeddingModel}" \
        -e GRS_SEQ_LEN="${toString cfg.embeddingMaxSeqLen}" \
        -e GRS_POOLING="${cfg.embeddingPooling}" \
        -e GRS_DEVICE="${cfg.embeddingDevice}" \
        -e PIP_DISABLE_PIP_VERSION_CHECK=1 \
        ${pythonImage} \
        bash -c '
          set -e
          echo "Installing optimum[openvino] + openvino-tokenizers..."
          pip install --quiet --no-warn-script-location \
            "optimum[openvino]>=1.20" "openvino-tokenizers" "transformers"
          python3 /pull.py
        '

      echo "$STAMP" > "$STAMP_FILE"
      echo "[graphrag-ovms-pull] Done."
    '';
  };
in
{
  options.services.graphrag-rs-npu = {
    enable = lib.mkEnableOption "graphrag-rs NPU embedding service (OVMS + static-model build)";

    user = lib.mkOption {
      type = lib.types.str;
      default = "graphrag-npu";
      description = ''
        User that owns the OVMS state dir. Set to your login user
        (e.g. "alice") if you want to read/write the model dir directly;
        otherwise the default synthetic system user is created.
      '';
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "users";
      description = "Group used for state ownership. Defaults to \"users\" so a normal login user has access.";
    };

    stateDir = lib.mkOption {
      type = lib.types.path;
      default = "/var/lib/graphrag-rs-npu";
      description = "Where the prebuilt static-shape model lives.";
    };

    embeddingModel = lib.mkOption {
      type = lib.types.str;
      default = "mixedbread-ai/mxbai-embed-large-v1";
      description = ''
        HuggingFace repo of the embedding model. Must be a stock-arch
        encoder (BERT, RoBERTa, XLM-RoBERTa, ModernBERT) that
        `optimum-intel` natively supports, with a pooling strategy that
        matches `embeddingPooling` (CLS or LAST — OVMS does not support MEAN).

        Default mxbai-embed-large-v1: 335M params, 512 ctx, native CLS
        pooling, 1024 dim, MTEB ~64.7. Verified to compile on Arrow Lake
        NPU 3 (per the in-house `npu-diagnose.sh static-search`).

        IMPORTANT: this model's output dimension MUST match the
        `services.graphrag-rs.embedding.dimension` set in the home-manager
        module (passed as EMBEDDING_DIM env var to graphrag-server).
        Mismatched dims silently corrupt the Qdrant collection.
      '';
    };

    embeddingMaxSeqLen = lib.mkOption {
      type = lib.types.int;
      default = 512;
      description = ''
        Static input sequence length baked into the IR before NPU compile.
        NPU 3 (Arrow Lake) requires fully-static shapes; this is the
        per-request token limit. Pick the largest your model+NPU pair
        handles. ModernBERT-style models have been verified at 2048.
      '';
    };

    embeddingPooling = lib.mkOption {
      type = lib.types.enum [ "CLS" "LAST" ];
      default = "CLS";
      description = ''
        Pooling strategy applied by OVMS before returning the embedding.
        Must match what the model was trained with — using CLS on a
        MEAN-trained model degrades quality significantly. OVMS does not
        support MEAN.
      '';
    };

    embeddingDevice = lib.mkOption {
      type = lib.types.enum [ "CPU" "GPU" "NPU" "AUTO" ];
      default = "NPU";
      description = ''
        OpenVINO target device. Fall back to "CPU" if the model fails to
        load on NPU (NPU 3 requires fully-static shapes; some models can't
        be reshaped successfully).
      '';
    };

    ports = {
      openvino = lib.mkOption {
        type = lib.types.port;
        default = 8000;
        description = "OVMS REST endpoint (OpenAI-compatible /v3/embeddings).";
      };
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open the OVMS port in the firewall (default: localhost-only).";
    };
  };

  config = lib.mkIf cfg.enable {
    # Synthetic system user; real login users must already exist (we just
    # ensure render/video group membership for NPU access).
    users.users.${cfg.user} = lib.mkMerge [
      (lib.mkIf (cfg.user == "graphrag-npu") {
        isSystemUser = true;
        group = cfg.group;
        home = cfg.stateDir;
        createHome = true;
      })
      { extraGroups = [ "render" "video" ]; }
    ];
    users.groups.graphrag-npu = lib.mkIf (cfg.group == "graphrag-npu") { };

    # Pin render/video GIDs so the OVMS container's --group-add references
    # stay correct. Conventional NixOS values; mkDefault means any other
    # module can override.
    users.groups.render.gid = lib.mkDefault 303;
    users.groups.video.gid = lib.mkDefault 26;

    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0750 ${cfg.user} ${cfg.group} -"
      "Z ${cfg.stateDir}/ovms-models 0750 ${cfg.user} ${cfg.group} -"
    ];

    # NPU kernel driver.
    boot.kernelModules = [ "intel_vpu" ];

    networking.firewall.allowedTCPPorts =
      lib.mkIf cfg.openFirewall [ cfg.ports.openvino ];

    virtualisation.podman.enable = lib.mkDefault true;

    # Pull oneshot: builds the static-shape model + tokenizer + graph at
    # first run (and whenever the stamped options change). Decoupled from
    # OVMS — runs once, OVMS then serves.
    systemd.services."graphrag-ovms-pull" = {
      description = "graphrag-rs-npu: build static-shape embedding model for OVMS";
      wantedBy = [ "podman-graphrag-ovms.service" ];
      before = [ "podman-graphrag-ovms.service" ];
      wants = [ "network-online.target" ];
      after = [ "network-online.target" ];
      serviceConfig = {
        Type = "oneshot";
        # Root: drives rootful podman + writes to the bind-mounted models dir.
        User = "root";
        ExecStart = "${pullScript}/bin/graphrag-ovms-pull";
        RemainAfterExit = true;
        TimeoutStartSec = "30min";
      };
    };

    virtualisation.oci-containers.containers."graphrag-ovms" = {
      image = ovmsImage;
      autoStart = true;
      ports = [ "127.0.0.1:${toString cfg.ports.openvino}:8000" ];
      volumes = [
        "${cfg.stateDir}/ovms-models:/models:ro"
      ];
      cmd = [
        "--rest_port" "8000"
        "--config_path" "/models/config.json"
      ];
      extraOptions = [
        "--user=0:0"
        "--device=/dev/accel/accel0"
        "--group-add=${toString config.users.groups.render.gid}"
        "--group-add=${toString config.users.groups.video.gid}"
      ];
    };
  };
}
